### ISSUE TITLE
Time

### ISSUE THREAD

**Issue by janrockstedt** [popeen/Home-Assistant-Custom-Component-Hemglass#3]
Would be nice to see the approx time and place.

**Comment by popeen** [comment]
Time and coordinates are available in the attributes of the stop. Since the coordinates are available as attributes you should also see it on your home assistant map.

Hope that helps
![image](https://github.com/popeen/Home-Assistant-Custom-Component-Hemglass/assets/5898388/1975b603-47af-44fb-b61a-e281b1d8733a)

**Comment by popeen** [comment]
In the next version the time will be shown in a better way due to changed device class, see https://github.com/popeen/Home-Assistant-Custom-Component-Hemglass/pull/7
